### PR TITLE
TASK: Adjust to Neos 4.1

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
Switching between versions in the package details doesn't work yet, might be that https://github.com/ttreeagency/OutOfBandRendering/pull/1 wasn't enough or something needs to be fixed here.

**Comment by kdambekalns** [comment]
See https://github.com/ttreeagency/OutOfBandRendering/pull/2 for the needed changes.

**Review by daniellienert — APPROVED** [review]
Looks good, haven't tested it

**Review by Sebobo — APPROVED** [review]
Marketplace browsing works fine for me locally with these changes 👍

**Pull request merged**
