### PR TITLE
BUGFIX: Wrong query structure for fulltext

### PR DESCRIPTION
**Pull request by Sebobo**
The previous structure broke the other fulltext queries on the neos.io website.

According to https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-function-score-query.html the structure must be like in the change.

### CODE REVIEW

**Comment by kdambekalns** [comment]
Just curious, but what

> other fulltext queries

are on the site?

**Comment by Sebobo** [comment]
@kdambekalns currently the showcase listing when you do a full text search.

**Review by kdambekalns — COMMENTED** [review]
Good by reading

**Review by kdambekalns — DISMISSED** [review]

**Comment by kdambekalns** [comment]
Sorry, but according to the docs `functions` and the other entries (`score_mode`, `boost_mode`, `query`) are on the same level. After that change, the latter are one above `functions`, though…

**Comment by Sebobo** [comment]
@kdambekalns  It was actually correct but the whole indentation was mixed up so I reindented the whole array now.

The three properties are next to functions.

**Review by kdambekalns — APPROVED** [review]

**Pull request merged**
